Update sonor.yml

diff --git a/.github/workflows/sonor.yml b/.github/workflows/sonor.yml
--- a/.github/workflows/sonor.yml
+++ b/.github/workflows/sonor.yml
@@ -1,21 +1,36 @@
 name: "sonar_cloud_scan_github_actions"
+
 on:
   workflow_dispatch:
+  pull_request:
 
 jobs:
-  DemoSonarCloudSCan:
+  DemoSonarCloudScan:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
-            fetch-depth: 0
+          fetch-depth: 0
+
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
         env:
-            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
-            SONAR_TOKEN: ${{ secrets.SONOR_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONOR_TOKEN }}
         with:
           args: >
-              -Dsonar.organization=bandarupriyanka
-              -Dsonar.projectKey=wdio_sonorcloudAnalysis
-              
+            -Dsonar.organization=bandarupriyanka
+            -Dsonar.projectKey=wdio_sonarcloudAnalysis
+
+      - name: Check Quality Gate
+        run: |
+          quality_gate_status=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=wdio_sonarcloudAnalysis" | jq -r .projectStatus.status)
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "Quality gate failed: $quality_gate_status"
+            exit 1
+          else
+            echo "Quality gate passed: $quality_gate_status"
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONOR_TOKEN }}
